elasticsearch:
    build: elasticsearch/
    container_name: elasticsearch
    command: elasticsearch -E network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

logstash:
    build: logstash/
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
      - "5044:5044"
      - "25826:25826"
    links:
      - elasticsearch

kibana:
    build: kibana/
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
