#!/bin/bash

# provision AWS EC2 machine using Ubuntu AMI

ssh-add ~/.ssh/elk-book-stack.pem
ssh-add -L

ansible-playbook -i hosts aws-provisioning/ec2-server.yml

# Install Docker and Docker-Compose on EC2 ubuntu instance

ansible-playbook -i hosts configure/install-docker.yml

# Spin up ELK stack on docker container

ansible-playbook -i hosts configure/install-elk.yml

# Install Wordpress App in Container

ansible-playbook -i hosts configure/install-Wordpress.yml
