wordpress:
 build: wordpress/
 container_name: wordpress
 ports:
   - "8081:80"
 links:
   - db:mysql
 external_links:
   - logstash
 log_driver: syslog
 log_opt:
   syslog-address: "tcp://logstash_ip:25826"

db:
 build: mysql/
 container_name: db
 environment:
   MYSQL_ROOT_PASSWORD: wordpress
