---

- name: Configure the instance
  hosts: vm
  remote_user: ubuntu
  gather_facts: False
  sudo: true


  tasks:
    - name: Update the machine
      apt: update_cache=yes

    - name: Install apt and ca certificates
      apt: name={{item}} state=installed
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: Add the gpg key
      command: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    - name: Check if /etc/apt/sources.list.d/docker.list file exist
      stat: path=/etc/apt/sources.list.d/docker.list
      register: var

    - name: Create /etc/apt/sources.list.d/docker.list file if not already present
      file: path=/etc/apt/sources.list.d/docker.list state=touch owner=root group=root mode=0644
      when: var.stat.exists is defined and not var.stat.exists

    - name: Edit /etc/apt/sources.list.d/docker.list file
      lineinfile: dest=/etc/apt/sources.list.d/docker.list regexp=^deb line='deb https://apt.dockerproject.org/repo ubuntu-trusty main'

    - name: Update the machine
      apt: update_cache=yes

    - name: Get kernel release
      shell: uname -r
      register: uname
  
    - name: Install linux image
      apt: name=linux-image-extra-{{ uname.stdout }} state=present

    ### Reboot the machine 
    
    - name: Update the machine
      apt: update_cache=yes

    - name: Install docker engine
      apt: name=docker-engine state=present

    - name: Start docker service
      service: name=docker state=started
    
    - name: Add user to docker group
      command: sudo usermod -aG docker ubuntu

    - name: Get docker compose
      shell: sudo curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose

    - name: Make docker-compose executable
      shell: chmod +x /usr/local/bin/docker-compose
