---

- name: Deploy ELK stack on Containers
  hosts: ec2
  remote_user: ubuntu
  gather_facts: False

  tasks:

    - name: change the default memory for the VM
      sudo: yes
      command: sysctl -w vm.max_map_count=262144

    - name: Copy elk-stack configuration
      copy: src=./docker/elk-stack  dest=/home/ubuntu/

    - wait_for:
        delay: 20

    - name: Build elk docker images using compose 
      command: docker-compose -f ~/elk-stack/elk-stack.yml build

    - name: Start docker container elk services
      command: docker-compose -f ~/elk-stack/elk-stack.yml up -d

