---

- name: Deploy ELK stack on Containers
  hosts: ec2
  remote_user: ubuntu
  gather_facts: False

  tasks:

    - name: change the default memory for the VM
      command: sudo sysctl -w vm.max_map_count=262144

    - name: Copy elk-stack configuration
      copy: src=./docker/elk-stack  dest=/home/ubuntu/

    - name: Build elk docker images
      command: sudo docker-compose -f "~/elk-stack/elk-stack.yml" build

    - name: Start docker container elk services
      command: sudo docker-compose -f "~/elk-stack/elk-stack.yml" up -d

