---

- name: Deploy Wordpress application
  hosts: ec2
  remote_user: ubuntu
  gather_facts: False


  tasks:

    - name: Copy wordpress application configuration
      copy: src=./docker/application dest=/home/ubuntu/

    - name: fecth logstash IP Address from container
      command: sudo docker inspect --format \{\{.NetworkSettings.IPAddress\}\} logstash
      register: logstash_ip

    - name: Update ip address in wordpress file to map the syslog to logstash
      lineinfile: 'dest=/home/ubuntu/application/wordpress.yml regexp="^   syslog-address"   line="   syslog-address: \"tcp://{{ logstash_ip.stdout }}:25826\""'

    - name: Build Wordpresss Applicaton docker images
      command: sudo docker-compose -f ~/application/wordpress.yml build

    - name: Start dokcer container application services
      command: sudo docker-compose -f ~/application/wordpress.yml up -d
